### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by godspeed-x** [SwapnilSoni1999/spotify-dl#101]
Hello, thank you for making this. 
1. Maybe a way to save the output directory so that there is no need to mention it everytime.
2. A flag that disables making a folder for a download.

**Comment by phyzical** [comment]
hey there, just for clarification what your requesting.

1. your after some sort of config you could set as the default to avoid providing -o each time correct?
2. A new flag that would enforce all songs are simply dumped directly into the output folder instead of abums, artists, playlist ect?

i think i can squeeze these into the current feature im working on

**Comment by godspeed-x** [comment]
Yes, that's correct.
Thank you

**Comment by godspeed-x** [comment]
@phyzical sorry for the late reply; i just tried it and it works perfectly.
