### ISSUE TITLE
Cover Image - Invalid data found when processing input

### ISSUE THREAD

**Issue by maej20** [SwapnilSoni1999/spotify-dl#157]
**Describe the bug**
Fails to download cover image properly, crashes with FFMPG error: "Invalid data found when processing input".  Restarting process completes song without issue.

**To Reproduce**
1. Run `spotifydl "<spotify-playlist-link>"`
2. Allow some songs to complete (sometimes 5, sometimes 30+)
3. Crash

**Expected behavior**
Playlist download completes without crashing

**Screenshots**
![image](https://user-images.githubusercontent.com/12991886/165191149-a2a50377-d3eb-4527-9f32-36a4439a6dd6.png)

**Desktop:**
 - OS: Linux 5.10.0-13-amd64 - Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
 - Browser:  Brave 1.37.116 (Chromium 100.0.4896.127)
 - Version: latest

**Additional context**
Crash seems to happen while adding the metadata attachments due to the cover image failing to download/being zero bytes at time of attachment. Near https://github.com/SwapnilSoni1999/spotify-dl/blob/master/lib/metadata.js#L33

**Comment by maej20** [comment]
I've tried fixing it myself, but it's completely random when it happens, can take quite a while to reproduce, and I'm not familiar enough with Javascript to debug at such a slow pace...figured someone else would probably know right off what to do

**Comment by phyzical** [comment]
thanks for the detailed report 👍 

does it happen with the same song or random songs by chance?

hmm maybe we can make a "fake" picture for replicating purposes to try a fix

**Comment by phyzical** [comment]
nah i think i remember trying to do the exact same thing to try and fix it.

just i think from memory it wasn't that the file saved was a zero byte but it was a malformed image that ffmpeg didn't like and cause it was so random i removed the code 😆 

though it could've been doing exactly what you were saying

if you want to try and build a fix and it happens again comment out the part that redownloads the image so that it stays borked `await downloadAndSaveCover(coverURL, coverFileName);`, then you should be able to keep trying a fix.

could just do a lazy while loop implementation with a counter until successful tbh the async in this project is all just being awaited, we never got around to making it super async due to things like rate limiting ect when going fully async
